version: '3.8'

services:
  simple-api:
    build: .
    container_name: simple-api-foundry
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
    restart: unless-stopped
    command: node simple-server.js